### PR TITLE
Change name of gay filter to rainbow

### PR DESCRIPTION
**Pull request by thekbb**
I use toilet at work for some stuff - the `--gay` filter adds appropriate whimsy.  I like it.
However, `--rainbow` would be better.

### CODE REVIEW

**Comment by yeahimfreaky** [comment]
You use toilet at work? Yeah.. TMI.

**Comment by thekbb** [comment]
Thanks for the excellent suggestion, @samhocevar.  Done:
toilet

**Comment by samhocevar** [comment]
Thanks for the additional effort.

**Comment by ghost** [comment]
> cringe



> pretty cringe bro ngl

this, so much this

**Pull request merged**
